development:
  adapter: postgresql
  database: receipt_application
  username: postgres
  password:
  host: localhost
  port: 5432

  #
  # development:
  #   adapter: postgresql
  #   database: receipt_application
  #   username: <%= ENV['PG_USER'] %>
  #   password: <%= ENV['PG_PASS'] %>
  #   host: localhost
  #   port: 5432
