development:
  adapter: postgresql
  database: receipt_application
  username: alvind
  password: alvind5635
  host: localhost
  port: 5432

  #
  # development:
  #   adapter: postgresql
  #   database: receipt_application
  #   username: <%= ENV['PG_USER'] %>
  #   password: <%= ENV['PG_PASS'] %>
  #   host: localhost
  #   port: 5432
